### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by PeterJoins** [paradiseduo/ApplicationScanner#12]
Traceback (most recent call last):
  File "/home/ApplicationScanner/lib/apk.py", line 45, in apkScan
    apkInfo(filePath)
  File "/home/ApplicationScanner/lib/apk.py", line 181, in apkInfo
    with open(yml, mode='r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ApplicationScanner/meiyou_VauCGw/apktool.yml'

这个怎么处理呢

**Comment by PeterJoins** [comment]
> 



> 用apktool命令解包之后看看成功没有

apktool可以解包成功，但是ApplicationScanner对所有的包都提示类似的错误

**Comment by PeterJoins** [comment]
> 我的意思是解包之后看一眼有没有apktool.yml这个文件

有

**Comment by paradiseduo** [comment]
可以切到git的上个节点换到2.6.1，最近只更了一个2.7.0。
我这边测2.7.0是好使的。

**Comment by PeterJoins** [comment]
Traceback (most recent call last):
  File "/home/ApplicationScanner/lib/apk.py", line 53, in apkScan
    c(filePath).scan()
  File "/home/ApplicationScanner/lib/Android/ReadFileCheck.py", line 32, in scan
    v = line.strip().split(',')[2].replace('}', '')
IndexError: list index out of range

**Comment by PeterJoins** [comment]
> 可以切到git的上个节点换到2.6.1，最近只更了一个2.7.0。 我这边测2.7.0是好使的。

我不记得我以前用的是哪个节点了，但是现在试了两个版本都不能使用了，扫描apk 和扫描aar都不能正常使用

**Comment by paradiseduo** [comment]
是所有的APP都不行吗？我这边用最新的代码测是可以的

**Comment by PeterJoins** [comment]
> 是所有的APP都不行吗？我这边用最新的代码测是可以的

随机试了三个应用，一个不能正常运行，其余两个有代码上的错误，ubuntu 环境，jdk1.8

**Comment by PeterJoins** [comment]
这个sdk 扫描是怎么使用的呢，有什么作用？

**Comment by gradient30** [comment]
查了下说是反编译时，资源加密需要加参数 -only-main-classes

**Comment by gradient30** [comment]
> 查了下说是反编译时，资源加密需要加参数-only-main-classes

与apktool.jar版本无关

**Comment by gradient30** [comment]
> 是所有的APP都不行吗？我这边用最新的代码测试是可以的

试了一下对于加密资源，windows中使用-only-main-classes，mac中使用-r 可以正常解包
但mac中改成-r后，又会报xml解析错误，如下
`Traceback (most recent call last):
  File "/Users/mac/ApplicationScanner-main/lib/apk.py", line 46, in apkScan
    permissionAndExport(filePath)
  File "/Users/mac/ApplicationScanner-main/lib/apk.py", line 97, in permissionAndExport
    tree = xml.dom.minidom.parse(XMLPath)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/minidom.py", line 1958, in parse
    return expatbuilder.parse(file)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 911, in parse
    result = builder.parseFile(fp)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 207, in parseFile
    parser.Parse(buffer, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0


Clean cache...
Finish`

**Comment by gradient30** [comment]
> > 是所有的APP都不行吗？我这边用最新的代码测试是可以的
> 
> 试了一下对于加密资源，windows中使用-only-main-classes，mac中使用-r 可以正常解包 但mac中改成-r后，又会报xml解析错误，如下 `Traceback (most recent call last): File "/Users/mac/ApplicationScanner-main/lib/apk.py", line 46, in apkScan permissionAndExport(filePath) File "/Users/mac/ApplicationScanner-main/lib/apk.py", line 97, in permissionAndExport tree = xml.dom.minidom.parse(XMLPath) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/minidom.py", line 1958, in parse return expatbuilder.parse(file) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 911, in parse result = builder.parseFile(fp) File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/xml/dom/expatbuilder.py", line 207, in parseFile parser.Parse(buffer, 0) xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0
> 
> Clean cache... Finish`

已确认是包体加固导致的，未加固的OK了。
