### ISSUE TITLE
windows环境下能安装使用吗？

### ISSUE THREAD

**Issue by zqf-dev** [paradiseduo/ApplicationScanner#16]
readme里介绍使用环境只能在mac 或者linux上，会出个windows环境平台使用的吗？

**Comment by paradiseduo** [comment]
俺没有用过Windows电脑办公啊。

**Comment by zqf-dev** [comment]
目前我在原基础上进行了改动，在windows环境平台上也可以检测：https://github.com/zqf-dev/ApplicationScannerWin
