### ISSUE TITLE
报错，找不到路径

### ISSUE THREAD

**Issue by Avenue-le** [paradiseduo/ApplicationScanner#21]
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\admin\\Downloads\\ApplicationScanner-main\\ApplicationScanner-main\\aaa_Tu4901

**Comment by paradiseduo** [comment]
![image](https://github.com/user-attachments/assets/98def54f-7db8-40b7-9b71-d8b848f6322c)
